name: vistw-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.52.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorama==0.4.6
      - datasets==3.6.0
      - dill==0.3.8
      - distro==1.9.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - filelock==3.18.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.170.0
      - google-auth==2.40.2
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface==0.0.1
      - huggingface-hub==0.32.0
      - idna==3.10
      - jinja2==3.1.6
      - jiter==0.10.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.82.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - together==1.5.8
      - tokenizers==0.21.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.52.3
      - triton==3.2.0
      - typer==0.15.4
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - xxhash==3.5.0
      - yarl==1.20.0
prefix: /mnt/home/ntuspeechlabtaipei1/miniconda3/envs/vistw-env
